### ISSUE TITLE
looks like it is copying garbage into |addr|

### ISSUE THREAD

**Issue by tfarina** [troglobit/lipify#1]
len might need to be shorter in strncpy(addr, ptr, len);

I got something like this:

(gdb) p ptr
$2 = 0xbfffee61 "95.251.46.206\004\b\b"

(gdb) p len
$3 = 256

This results in it showing garbage in the output:

$ ./ipfiy
95.251.46.206:

or 

$ ./ipfiy
95.251.46.206m

**Comment by troglobit** [comment]
Thanks for the report! In 480a700 I added address family validation, which should fix your problem. 
Please let me know if it does so I can push out a new release :smiley:

**Comment by tfarina** [comment]
@troglobit Awesome! This fixes the problem for me. Thanks for the quick solution.

**Comment by troglobit** [comment]
No problem, thank you for the report. Will prepare a release asap!
